### ISSUE TITLE
Remove the footer

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/cozy-sun-bear#101]
While testing with users, it was reported that the copyright and publisher information was not helpful and confused readers. They thought this information was in relation to the platform, not the book.

- [ ] Remove the footer
- [ ] Ensure this information is contained in the "Information" widget

**Comment by respinos** [comment]
The footer is just a control; cozy-sun-bear just needs to be invoked without the footer.

**Comment by jmcglone** [comment]
👍  will close here -- [added to heliotrope](https://github.com/mlibrary/heliotrope/issues/1367)
