### ISSUE TITLE
Modify citation widget to pre-format citations

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/cozy-sun-bear#102]
According to librarian testers, all three citation formats (MLA, CMS, APA) are wrong. [Really?! We lifted these examples from the the OWL Purdue guide](https://github.com/mlibrary/cozy-sun-bear/issues/39).

To avoid incorrectly formatted citations:

- [x] modify the citation widget to accept pre-formatted citations
- [x] remove the algorithm to format citations based on EPUB metadata.

**Comment by respinos** [comment]
Putting another plug that cozy-sun-bear should be given citations pre-formatted and just display them. :plug:

**Comment by jmcglone** [comment]
In a parking lot discussion on 12/8, we decided to modify the citation widget to pre-format citations. From @respinos it might look something like this:

```
    reader = cozy.reader(document.createElement('div'), {
      engine: 'mock',
      href: 'mock.epub',
      metadata: {
        citations: [
          { format: 'MLA', text: "Mock, Alex. <em>The Mock Life</em>. University Press, 2017." },
          { format: 'APA', text: "Mock, A. (2017). <em>The Mock Life</em>. Ann Arbor, MI: University Press." },
          { format: 'Chicago', text: "Mock, Alex. <em>The Mock Life</em>. Ann Arbor, MI: University Press, 2017." }
        ]
      }
```

This method allows more control over the citation formatting from the user end and relies less on an algorithm to format the citation, which could potentially spit out incorrect formatting if the metadata is incomplete.

The ticket has been re-named and acceptance criteria has been re-written to reflect this.

**Comment by jmcglone** [comment]
The heliotrope portion has been removed and moved to [H#1547](https://github.com/mlibrary/heliotrope/issues/1547)
