### ISSUE TITLE
Scroll does not work on iPhone

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/cozy-sun-bear#106]
When viewing a book in CSB on an iPhone, scroll does not work. It is hard to describe, but when the finger attempts to scroll the page contents, it is as if you are scrolling the entire browser down, rather than the contents of the iframe. 

To note, this does not happen on Android devices and was happening on iPhones 8, 7, 6 and then I stopped there.

**Comment by respinos** [comment]
Mobile Safari appears to need  `-webkit-overflow-scrolling: touch` on (one) of the wrapping divs.
