### ISSUE TITLE
Event handling for WebGL

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/cozy-sun-bear#115]
Setup an event listener to catch when someone activates a WebGL file.

**Comment by respinos** [comment]
@jmcglone How does this look for the heliotrope side?

```
// reader is instantiated...
var unity_click_handler = function(event) { ... };
reader.hooks.content.register(function(contents) {
  var links = contents.body.querySelectorAll("a[data-unity]");
  for(var i =0, n = links.length; i < n; i++) {
    var link = links[i];
    link.addEventListener('click', unity_click_handler);
}
```

**Comment by jmcglone** [comment]
👍  looks good to me. Does anything need to happen on the CSB side of things?

**Comment by respinos** [comment]
This will be evolving into this sequence:

```
var click_handler = function(target) { ... };
reader.on('ready:contents', function(contents) {
    var links = contents.content.querySelectorAll("a[data-uid]");
    for(var i =0, n = links.length; i < n; i++) {
       var link = links[i];
       link.addEventListener('click', click_handler);
    }
})

reader.start();
```

**Comment by jmcglone** [comment]
@respinos ☝️  looks good. I'm a little fuzzy on what needs to happen to move forward. Do we just add this to heliotrope's epub view that loads CSB and create a modal widget that contains the WebGL?

**Comment by respinos** [comment]
`click_handler` has to evolve to however the WebGL is viewed --- modal? Or splitting the main panel in half by adding another `<div>` before/after the epub viewer.
