### ISSUE TITLE
License infringement

### ISSUE THREAD

**Issue by eshellman** [mlibrary/cozy-sun-bear#117]
cozy-sun-bear does not appear to be in compliance with the licenses of code it incorporates, as it does not appear to include the required license documents. For example, epub.js uses a BSD 2-clause license https://github.com/futurepress/epub.js/blob/master/license. Readium is distributed with a BSD 3-clause license https://github.com/readium/readium-js/blob/master/license.txt To avoid copyright infringement, the repo should include the incorporated licenses or remove all code copied from third party projects.

**Comment by jmcglone** [comment]
@eshellman thanks for pointing out the missing license -- this actually will get us to do some refactoring so we can be sure to add a correct and compliant license, but this is on our radar. You can follow the progress at #118.

**Comment by eshellman** [comment]
Happy to be of service; I was trying to figure out what code you were actually using for the epub reader. There's a team working on https://github.com/EbookFoundation/regluit that hopes to add an epub reader in the next couple of months.

**Comment by jmcglone** [comment]
Resolved by #119
