### ISSUE TITLE
Support for skip links in host applications

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/cozy-sun-bear#121]
Enable support for host applications (like heliotrope) to set up and fill in skip links via `<div>`s that link to the main viewer and open the table of contents panel.

**Comment by respinos** [comment]
@jmcglone - adding the `skipLink` to the `Contents` control, which really is handling the event. Thoughts?

```
cozy.control.contents({ region: 'top.toolbar.left', skipLink: '.skip' }).addTo(reader);
```

**Comment by jmcglone** [comment]
That seems right to me!
