### ISSUE TITLE
Investigate support for EPUBs with multiple renditions

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/cozy-sun-bear#126]
What needs to happen to the CSB code in order for it to support EPUBs that contain valid multiple renditions?

**Comment by respinos** [comment]
The simple:

- some changes to epub.js to support reporting available renditions and then opening a given rendition
- make renditions available in cozy-sun-bear: would the Preferences panel work?

The mysterious:
- syncing progress between renditions

That's going to be a debate. The temptation will be to replicate the fixed-width layout with plaintext, but EPUB  fixed-layout rendering is *not* set up for that (at least, not the paginated view).
