### ISSUE TITLE
Lots of issues in Safari 11.0.2

### ISSUE THREAD

**Issue by jgmorse** [mlibrary/cozy-sun-bear#128]
I haven't tried any browsers besides Safari 11.0.2 and Chrome (Mac).

- [x] When clicking the Read Book link and going to https://www.fulcrum.org/epubs/t722h883s?locale=en#/ops/xhtml/cover.xhtml, the content never loads in the CSB viewport (load animation keeps going for minutes).
- [x] Clicking any link in the TOC will load that section, but without the CSB wrapper/theming/widgets.

- [x] Clicking any search result gets a 500 error.

**Comment by conorom** [comment]
Fixed by @respinos by removing usage of Promises.finally. Tested in heliotrope.
