### ISSUE TITLE
Embedded Leaflet performance in Safari 11

### ISSUE THREAD

**Issue by conorom** [mlibrary/cozy-sun-bear#129]
When browsing the NYU Press EPUB in Safari 11, the Leaflet maps embedded in iframes have all their "actions" slowed down by a huge factor, e.g. button pan/zoom, double-click zoom, mouse click-and-drag pan etc. In fact, at first I thought mouse dragging was broken completely but it's actually just working at super slow speed. If you click and drag a bit, wait several seconds it will eventually move. Let go and it will snap back after about 5 or 6 seconds.

The Leaflet maps on the Heliotrope asset pages work fine in Safari, as do the embedded views when not in CSB. The quickest way to see this is by directly loading the EPUB content, e.g.:
https://www.fulcrum.org/epubs/t722h883s/ops/xhtml/15_Conclusion.xhtml

There are some hits for problems with `overflow: hidden` in Safari/WebKit and other stuff about forcing 3D acceleration (with hacks) when encountering similar problems. Nothing really jumps out at me as the answer right now, though.

We have several layers of `overflow: hidden` in place with the embed seen above. Then some more layers in CSB. I've no idea if that has anything to do with it.

**Comment by respinos** [comment]
http://openaccessbooks.nyupress.org/book/9780814731956/ for comparison; the positioning of the iframes is quite different (absolutely positioned).

**Comment by respinos** [comment]
...and to this point: the latest Safari Technology Preview doesn't have this issue. ¯\_(ツ)_/¯

**Comment by conorom** [comment]
I took a look through the release notes for Webkit to see if I could find the pertinent fix, but gave up after looking at several releases:
https://webkit.org/blog/

This tweak will cover the problem for heliotrope. Will keep an eye out for the problem to resolve in Safari 11:
https://github.com/mlibrary/heliotrope/pull/1550/commits/ba8f0b8574eeccbfa47807a7b753350ba98703b6

**Comment by conorom** [comment]
Problem still exists for the current release, Safari 11.0.3 (13604.5.6).

**Comment by conorom** [comment]
I guess as the "fix" is in heliotrope I'll put a new watch ticket in heliotrope to eventually remove said "fix".
