### ISSUE TITLE
Search Improvement: When user submits search, the search modal opens

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/cozy-sun-bear#136]
As a user, I'd like to know that my search has been accepted and is being processed.  

When a user submits a search, open the search modal and display a loading animation until search results are returned.

**Comment by jmcglone** [comment]
@respinos Does PR #138 resolve this issue? https://github.com/mlibrary/cozy-sun-bear/pull/138

**Comment by respinos** [comment]
PR #138 addresses this.
