### ISSUE TITLE
Support for pre-paginated EPUBs

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/cozy-sun-bear#149]
Support for the display of fixed layout/page image EPUBs

- [ ] as a user I can zoom in/out the stage
- [ ] as a user I can switch between different renditions #126 
- [ ] as a user I can view pre-paginated books, scrolling continuously

**Comment by respinos** [comment]
- [ ] as a user with a narrow screen, a pre-paginated book is opened in `scrolled-doc` for maximum viewability
