### ISSUE TITLE
Refactor the Preferences widget "Display" fieldset

### ISSUE THREAD

**Issue by respinos** [mlibrary/cozy-sun-bear#151]
Our current *Display* preferences let you switch the *flow* between

* paginated
* scrolled-doc

In epub.js, rendering has a manager: the default, which only loads one document at a time, or continuous, which fetches documents automatically. This manager is independent of the flow setting, although obviously the continuous manager matches scrolled-doc behavior more naturally.

Possibilities:

- [ ] add `auto` option, so the user can change text size preferences without also persisting _this_ book's flow (this should be a given)
- [ ] Option 1
  - user can choose between `paginated` and `scrolled-doc`
  - user can choose between `default` and `continuous` (and good luck to us coming up with clear labels!)
- [ ] Option 2
  - user can choose between `paginated` and `scrolled-doc`
  - (based on that choice, cozy-sun-bear will switch between `default` and `continuous`)

**Comment by tbelc** [comment]
My vote is for option #2. If I understand it correctly, this would indicate which choice was made and an opportunity to change it if necessary. Otherwise, #1.

**Comment by respinos** [comment]
@tbelc - I edited the ticket to more accurately affect what I was trying to describe.

Is `continuous` only advantageous for users using the mouse/trackpad to scroll the `scrolled-doc` flow? (Now that the next/previous navigation is fixed.)

**Comment by jmcglone** [comment]
Agree, #2 seems the best option here. 

Also agree that continuous makes sense only for `scrolled-doc`.

**Comment by jgmorse** [comment]
Also agree that Option 2 is the better. (Grammar!)
