### ISSUE TITLE
Check font support

### ISSUE THREAD

**Issue by jgmorse** [mlibrary/cozy-sun-bear#26]
- [x] Test that embedded fonts display correctly.
- [x] Test UTF-8 / UTF-16 compatibility.

As written by Becky Welzenbach:
"Does the work require the use of fonts that are not included in standard web browsers/ operating systems?"

**Comment by respinos** [comment]
EPUBs list their custom fonts in `package.opf`:

```<item id="epub.embedded.font.1" href="fonts/UbuntuMono-B.ttf" media-type="application/vnd.ms-opentype"/>```

and referred to in the package CSS files: 

```font-family: "Ubuntu Mono", monospace;```

The epub library (that we wrap) parses the package.opf and adds the `<link>` elements to load the custom font in its HTML view (by default, an `<iframe>`).

**Comment by jmcglone** [comment]
Double-check fonts working in Firefox

**Comment by jmcglone** [comment]
Examples of HOB titles with non-Roman characters in CSB:

![screen shot 2017-11-29 at 1 23 08 pm](https://user-images.githubusercontent.com/1686111/33392008-c5250eea-d508-11e7-9ad4-1f1b914168c7.png)
![screen shot 2017-11-29 at 1 17 22 pm](https://user-images.githubusercontent.com/1686111/33392010-c531e2aa-d508-11e7-97a7-16e4107dd26e.png)
