### ISSUE TITLE
Assemble representative EPUBs

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/cozy-sun-bear#3]
- [x] obtain a DCB EPUB that is fully encoded and EPUB3
- [x] obtain EPUBs that represent outliers in terms of design or embedded content

**Comment by jgmorse** [comment]
From Jillian: " Just downloaded some relatively recent ones down from BV and zipped them in a folder in Box. Not a very scientific approach in choosing but I know some had a lot of art, some a lot of tables, at least one had a photo insert, one had color art in ebook and B&W in text. Let me know if more would be useful."

https://umich.app.box.com/s/93qxn3d6tr7d3jwjxzz1qkubqkoiewhg
