### ISSUE TITLE
Add citation widget

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/cozy-sun-bear#39]
As a user, I should be able to get a pre-formatted citation of the book I'm reading in MLA, APA, or Chicago Style formatting. I should be able to easily copy the text and paste it, or send it to a citation manager like Zotero.

- [ ] Base the citation on information that is pulled from the EPUB file itself
- [ ] Create a citation widget that provides a citation of the title formatted in MLA, APA, or Chicago
- [ ] The selected citation should copy to a users clipboard when a user selects to copy citation
~- [ ] The selected citation should import to Zotero when a user selects to import citation~

This ticket requires the following items first:
- [x] wireframes and user flows of the citation widget described below
- [x] examples of book citation formatting in MLA, APA, Chicago Style

**Comment by jmcglone** [comment]
## MLA general format
Last Name, First Name. _Title of Book_. Publisher, Publication Date, DOI/Handle.

## APA general format
Author, A. A. (Year of publication). _Title of work: Capital letter also for subtitle_. Location: Publisher. DOI/Handle.

## Chicago general format
Lastname, Firstname. _Title of Book_. Place of publication: Publisher, Year of publication. DOI/Handle.

## Book with one author
### MLA
Gleick, James. _Chaos: Making a New Science_. Penguin, 1987, https://doi.org/10.3998/fulcrum.123456.

### APA
O'Neil, J. M. (1992). _Men's and women's gender role journeys: A metaphor for healing, transition, and transformation_. New York, NY: Springer. https://doi.org/10.3998/fulcrum.123456.

### Chicago
Faulkner, William. _Absalom, Absalom!_. New York: Vintage Books, 1990. https://doi.org/10.3998/fulcrum.123456.

## Book with more than one author
### MLA
Gillespie, Paula, and Neal Lerner. _The Allyn and Bacon Guide to Peer Tutoring_. Allyn and Bacon, 2000, https://doi.org/10.3998/fulcrum.123456.

### APA
Calfee, R. C., & Valencia, R. R. (1991). _APA guide to preparing manuscripts for journal publication_. Washington, DC: American Psychological Association. https://doi.org/10.3998/fulcrum.123456.

### Chicago
Lash, Scott, and John Urry. _Economies of Signs & Space_. London: Sage Publications, 1994.  https://doi.org/10.3998/fulcrum.123456.

## Book with more than three authors
### MLA
Wysocki, Anne Frances, et al. Writing New Media: Theory and Applications for Expanding the Teaching of Composition. Utah State UP, 2004, https://doi.org/10.3998/fulcrum.123456. 

### APA
Wysocki, A.F., et al. (2004). _Writing new media: Theory and applications for expanding the teaching of composition_. Utah State UP. https://doi.org/10.3998/fulcrum.123456. 

### Chicago
Wysocki, Anne Frances, et al. _Writing New Media: Theory and Applications for Expanding the Teaching of Composition_. Logan, UT: Utah State UP, 2004. https://doi.org/10.3998/fulcrum.123456. 

## A Translated Book
### MLA
Foucault, Michel. _Madness and Civilization: A History of Insanity in the Age of Reason_. Translated by Richard Howard, Vintage-Random House, 1988, https://doi.org/10.3998/fulcrum.123456.

### APA
Laplace, P. S. (1951). _A philosophical essay on probabilities_. (F. W. Truscott & F. L. Emory, Trans.). New York, NY: Dover. (Original work published 1814). https://doi.org/10.3998/fulcrum.123456.

### Chicago
Cortázar, Julio. _Hopscotch_. Translated by Gregory Rabassa. New York: Pantheon Books, 1966. https://doi.org/10.3998/fulcrum.123456.

## An Edition of a Book
### MLA
Crowley, Sharon, and Debra Hawhee. _Ancient Rhetorics for Contemporary Students_. 3rd ed., Pearson, 2004, https://doi.org/10.3998/fulcrum.123456.

### APA
Helfer, M. E., Kempe, R. S., & Krugman, R. D. (1997). _The battered child_ (5th ed.). Chicago, IL: University of Chicago Press. https://doi.org/10.3998/fulcrum.123456.

### Chicago
Crowley, Sharon, and Debra Hawhee. _Ancient Rhetorics for Contemporary Students_. 3rd ed., London: Pearson, 2004. https://doi.org/10.3998/fulcrum.123456.

## Edited Book
### MLA
Hill, Charles A., and Marguerite Helmers, editors. _Defining Visual Rhetorics_. Lawrence Erlbaum Associates, 2004, https://doi.org/10.3998/fulcrum.123456.

### APA
Duncan, G. J., & Brooks-Gunn, J. (Eds.). (1997). _Consequences of growing up poor_. New York, NY: Russell Sage Foundation.

### Chicago
Greenberg, Joel, ed. _Of Prairie, Woods, and Water: Two Centuries of Chicago Nature Writing_. Chicago: University of Chicago Press, 2008.

## Multivolume Work
### MLA
Quintilian. _Institutio Oratoria_. Translated by H. E. Butler, Loeb-Harvard UP, 1980. 4 vols, https://doi.org/10.3998/fulcrum.123456. 

### APA
Wiener, P. (Ed.). (1973). _Dictionary of the history of ideas_ (Vols. 1-4). New York, NY: Scribner's.

**Comment by jmcglone** [comment]
When a user clicks on "Get Citation" a full-screen modal with radio buttons to select citation formatting is displayed (shown below). Rendered text changes based on selected format, displaying the text that will be copied to the user's clipboard. Show a success message when "Copy Citation" button is clicked. Give the user the ability to close/exit the modal in top right corner.

![epubrenderer-getcitation](https://cloud.githubusercontent.com/assets/1686111/26172663/2d4b3cba-3b17-11e7-9f4a-3c3f8e7407cf.png)

**Comment by jmcglone** [comment]
@respinos examples and mockup provided. I have modified the acceptance criteria to only deal with copying citations at this point. I will create a separate ticket for exporting to citation managers with a more detailed list of citations managers we should support.

**Comment by jmcglone** [comment]
This sounds great to me. Regarding deactivating the citation widget...this is a good point that some EPUBs might not have the required metadata. 

Another option: the citation modal displays a message like "The EPUB file has insufficient metadata to form a complete citation" (can obviously be wordsmithed) to avoid confusing readers where one title might have a citation widget and another would be missing the citation widget.

**Comment by jmcglone** [comment]
@respinos does PR #51 close this? If there is additional work with the citation widget we can create a new ticket specifying what those requirements are

**Comment by respinos** [comment]
Yes. Closing.
