### ISSUE TITLE
Add share widget

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/cozy-sun-bear#43]
As a user, I'd like to be able to share a permalink of the EPUB I'm reading to various social media outlets.

- [x] when a user clicks on a share icon, they are shown a modal dialog that presents options of places to post the permalink (DOI or handle) of the EPUB asset
- [x] for now, could follow the sharing conventions featured in heliotrope (see[ this file for a list/specs](https://github.com/mlibrary/heliotrope/blob/b74bb31dabffcdb0c030984298c6fe101c6974ae/app/views/curation_concerns/file_sets/_show_actions.html.erb#L32))
- [x] does not need additional icons for each social media site
- [x] should use the `share` open iconic icon via `<span class="oi" data-glyph="share-boxed"></span>`
- [x] User flow:  click "share icon" > modal > click link to social site > opens pre-filled out info in new window & closes modal
- [x] Share sites: Twitter, Facebook, Google+, Reddit, Mendeley, Cite U Like

**Comment by mbakeryo** [comment]
It does not appear that we have to have this in place by end of March, so I moved it to spring.

**Comment by jmcglone** [comment]
@respinos No mockups, but I think the acceptance criteria should be enough to get started.

**Comment by jmcglone** [comment]
After much playing around and thinking, I have decided to implement this on the Heliotrope end of things using a dropdown menu.
