### ISSUE TITLE
Add full-screen widget

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/cozy-sun-bear#44]
As a user, I want to enlarge the size of the EPUB viewer to the full size of my screen and still maintain some of the tools in the application.

- [x] When a user clicks the full-size icon the EPUB viewer fills the height and width of the users screen
- [x] a method to close out of full-screen mode is presented to the user
- [x] clicking close full-screen mode returns the viewer to the browser and maintains the current state of where the user was in the EPUB
- [x] uses the `fullscreen-enter` icon via `<span class="oi" data-glyph="fullscreen-enter"></span>` for the full screen widget
- [x] uses the `fullscreen-exit` icon via `<span class="oi" data-glyph="fullscreen-exit"></span>` to return to the EPUB viewer to its initial size

This ticket requires the following items first:
- [x] a mockup of the EPUB viewer/reader and its menu in full screen mode

**Comment by respinos** [comment]
Triggering full screen on `#reader` isn't half bad (although cozy is messed up when you exit fullscreen mode):

![screen shot 2017-07-20 at 4 26 27 pm](https://user-images.githubusercontent.com/537867/28437333-393becd0-6d68-11e7-993e-4d29443722ea.png)

https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API

**Comment by jmcglone** [comment]
This one needs to be widgetized - ie an icon added to it
