### ISSUE TITLE
Extend preferences widget

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/cozy-sun-bear#45]
As a user, I would like to adjust the display of the text based on my reading preferences. I should be able to increase/decrease the font size, switch to a dark background and light text (and vice versa).

- [x] when a user clicks the preferences cog, they see a modal dialog that allows them to increase or decrease the font size. When clicking the increase or decrease, this change is reflected on save.
- [x] when a user clicks the preferences cog, they see a modal dialog that allows them to switch to a dark background/light text. When clicking the toggle the background change is reflected on save.
- [x] both options appear in the existing preferences modal dialog that contains text display preferences

This ticket requires the following items first:
- [x] Mockups of the preferences modal dialog that contains text increase/decrease and background/text color changes.
- [x] a color for the dark background and a color for the light text.

**Comment by respinos** [comment]
Some concerns about the requirement to do live updates --- I'm not sure either of our engines can do that. The Readium cloud app (which has the most built-out UI) has a "preview the settings" approach:

![image](https://cloud.githubusercontent.com/assets/537867/25806272/a3f13ee4-33d0-11e7-9344-ee243ad3cbd6.png)

**Comment by jmcglone** [comment]
@respinos This wasn't a hard requirement, just one that I have noticed in other applications and seems very nice. If we don't think it is possible, then I'll remove.
