### ISSUE TITLE
Determine need for search widget

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/cozy-sun-bear#46]
We are undecided on whether a search widget should exist in CSB. If it were, ideally this would take the form of a search widget that searches inside the EPUB text and provides the user with a clickable result set that navigates them to points in the EPUB file.

Question: how much of the cozy "chrome" is active with search results?
Question: what implications might this have for search when deployed through HathiTrust or Heliotrope?

**Comment by respinos** [comment]
Raising the question whether the cozy dialog system changes some of these questions (re: chrome).

**Comment by mbakeryo** [comment]
Closing as work was done on other tickets. (And our decision was to have search in CSB.)
