### ISSUE TITLE
Add visual indicators of page load

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/cozy-sun-bear#54]
When a chapter load is delayed, display a loading icon or skeleton screen to indicate to the reader that the file is in the process of loading.

The problem of slow loads is commonly seen in heliotrope's deployment of csb.

**Comment by respinos** [comment]
Skeleton screen is tempting; I'm concerned that there's no consistent "shape" of what's being rendered.

If it's a loading icon, you can assume the existence of `<div class="cozy-status-loading">`.

**Comment by jmcglone** [comment]
I was thinking skeleton screen for the title / chapter. You don't notice the empty space when running locally but in heliotrope it's bad. This is the screen while the EPUB loads the first chapter of an HEB title in heliotrope:

![screen shot 2017-06-09 at 10 13 50 am](https://user-images.githubusercontent.com/1686111/26979357-80fba7e0-4cfc-11e7-852c-5dc9e03066bb.png)

**Comment by respinos** [comment]
Yikes. FYI: there's a dance with waiting for slots to be filled as metadata streams into the reader before calculating the available height for the epub.js slot. Asynchronous data is such fun.

**Comment by respinos** [comment]
![image](https://user-images.githubusercontent.com/537867/27104926-ab32b6e0-505b-11e7-84ce-23d89ece4865.png)
