### ISSUE TITLE
Resizing window sometimes returns user to title page

### ISSUE THREAD

**Issue by jgmorse** [mlibrary/cozy-sun-bear#55]
Intermittently, resizing the ebook reader will turn the page back to the title page.  It is very inconsistent; I just recreated the behavior in both Chrome and Safari, on 2 different Macs, but it only happens one out 20 resizes or so.

- [x] Resizing the browser window alone should never cause a different page to appear.

**Comment by respinos** [comment]
Possibly a larger issue with fixed-layout. For future research 

![image](https://user-images.githubusercontent.com/537867/27085440-3f79d930-501d-11e7-9794-0718006e2862.png)

**Comment by respinos** [comment]
Closed with PR #57.
