### ISSUE TITLE
Book location/reading progress indicator

### ISSUE THREAD

**Issue by gkostin1966** [mlibrary/cozy-sun-bear#64]
As a reader, I would like a visual indicator to know where I am in the EPUB relative to the beginning and end of the EPUB. This is especially helpful when following search results to points in the EPUB.

- [x] provide a progress bar visual indicator at the bottom of the EPUB reader. The further into the EPUB the more the progress bar is filled. 
- [x] progress bar adjusts forward as a reader "pages" forward through the EPUB
- [x] progress bar adjust backward as a reader "pages" backward through the EPUB
- [x] clicking on a point in the progress bar takes you to that approx. location within the EPUB (?)

**Comment by respinos** [comment]
We have a widget, but it only has default styling.

**Comment by sethaj** [comment]
Although this is in CSB, I think we still need to add this widget to heliotrope.
