### ISSUE TITLE
FF 50: 2 column display does not work

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/cozy-sun-bear#75]
In Firefox 50 (and 51), 2 column paging (default display) does not work. Text is set in one column and clicking the right-arrow to page foward takes you to the next section. This also impacts full screen mode. 

Firefox 50:
![bs_win10_firefox_50 0 4](https://user-images.githubusercontent.com/1686111/30652122-8bbadf9e-9df5-11e7-8d7e-a5686b170322.jpg)

Firefox 50 console:

![bs_win10_firefox_50 0 3](https://user-images.githubusercontent.com/1686111/30652078-70bb80c2-9df5-11e7-9766-8d3c351fdd51.jpg)

Firefox 52 console:

![bs_win10_firefox_52 0](https://user-images.githubusercontent.com/1686111/30652316-188b6d62-9df6-11e7-86eb-27cd07b1a7f5.jpg)

- [ ] enable 2-column view and fix paging for FF 50 and later
- [ ] if not possible, default viewer to scroll mode for browsers < FF52

**Comment by respinos** [comment]
Add prefixed column attributes for legacy browsers (in epub.js)

**Comment by respinos** [comment]
^ ignore that

Instead: proposing that cozy-sun-bear sniffs what CSS the browser supports and then forces presentation, e.g. if the browser doesn't support non-prefixed CSS column properties, cozy-sun-bear can only present in `scrolled-doc`view.
