### ISSUE TITLE
FF 50: Can't navigate to search result

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/cozy-sun-bear#76]
In FF 50 (and 51), when I click on a search result in the results overlay, the page I am trying to navigate to never loads. 

![bs_win10_firefox_50 0 5](https://user-images.githubusercontent.com/1686111/30652965-c8dc08ce-9df7-11e7-867e-2641bd53ea32.jpg)

Console error message:
`TypeError: this.element.dataset is undefined` in line 106 of application.js

Might be related to issue with 2-column display. Navigating to search results works in FF52.

- [ ] Fix search result navigation for FF 50 and later
- [ ] If cannot be fixed, determine how to handle (perhaps a warning message for browsers on < FF 52?)

**Comment by respinos** [comment]
Seems to be related to highlighting.

**Comment by respinos** [comment]
Fixed by PR #88
