### ISSUE TITLE
Chrome 54: Can't navigate to search result

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/cozy-sun-bear#77]
In Chrome 54, when I click on a search result in the results overlay, the page I am trying to navigate to never loads.

![bs_win10_chrome_54 0](https://user-images.githubusercontent.com/1686111/30662331-ba87383a-9e14-11e7-8ac9-105d95bf2555.jpg)

Console error message:
`Uncaught (in promise) TypeError: Cannot set property 'epubcfi' of undefined(...)` on line 106 of application.js

May be related to issue we also see in < FF52 (#76)

- [ ] Fix search result navigation for Chrome 54 (works in Chrome 55)
- [ ] If cannot be fixed, determine how to handle (perhaps a warning message for browsers < Chrome 55?)

**Comment by respinos** [comment]
Fixed by PR #88
