### ISSUE TITLE
Safari 10: Button height does not fill containers

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/cozy-sun-bear#78]
On Safari 10.1 (and 9.1) and IE11, CSB buttons in the second menu are not filling the height of their respective container:

![bs_macelc_safari_9 1 1](https://user-images.githubusercontent.com/1686111/30664389-8772f752-9e1b-11e7-829e-fd6e928c4edf.jpg)

- [x] Modify CSS rules so that buttons fill the height of the container they are placed in on Safari 9.1+

**Comment by jmcglone** [comment]
This is not a problem with the most recent version of Safari (11)

**Comment by jmcglone** [comment]
Documented here https://stackoverflow.com/questions/19119910/safari-height-100-element-inside-a-max-height-element#19121022

**Comment by jmcglone** [comment]
This is a Safari specific bug -- should we fix it?

**Comment by respinos** [comment]
Following https://stackoverflow.com/questions/33636796/chrome-safari-not-filling-100-height-of-flex-parent I had the best success using nested flex containers ... but that introduced new artifacts (wider buttons).

**Comment by jmcglone** [comment]
Fixed in IE 11. Updating ticket title.

![bs_win10_ie_11 0 2](https://user-images.githubusercontent.com/1686111/38812779-3e21c018-415b-11e8-9586-6d38225b0d67.jpg)

**Comment by jmcglone** [comment]
I have a fix for this in `bug/safari-10-flex-height` branch and confirm is fixes the bug (using nested flexes), but need to throughly test across browsers to make sure no new bugs are introduced.

- [ ] pull branch into heliotrope
- [ ] Safari 9, 10, 11
- [ ] Edge 15, 16
- [ ]  IE 10, 11
- [ ] Chrome
- [ ] Firefox
