### ISSUE TITLE
Edge 14+: Can't navigate to search result

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/cozy-sun-bear#80]
In Edge 14 and 15, when I click on a search result in the results overlay, the page I am trying to navigate to never loads.

Edge 14
![bs_win10_edge_14 0](https://user-images.githubusercontent.com/1686111/30665923-b71ca714-9e20-11e7-8415-cabad11b4dec.jpg)

Edge 15
![bs_win10_edge_15 0](https://user-images.githubusercontent.com/1686111/30665928-bdbf4126-9e20-11e7-9c67-6f20716a0f65.jpg)

Console logs a very strange `Permission denied` message that is hard to investigate

May be related to #76 and #77

- [ ] Fix search result navigation for Edge 14 and 15
- [ ] If cannot be fixed for 14, at least fix for 15 and perhaps create a warning browser message for browsers < Edge 15

**Comment by sethaj** [comment]
This is what it's upset about, line 111 of contents.js in epub.js

I think this getting triggered for every highlighted search result. But I'm not sure why this would be considered `Permission denied`

![ie-edge-permission-denied.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/570be388559d15130075b8b1/125516c66e82c728ace21e0d46e191d7268684acc2f9ba51a954e3872049293e2d01ad227581a164fd52690e050a1de853524d41faad8d2da7e23b248a0f5aec836b5774c63944acba841cad1da862da11d1e9e1d30695aa2f2ff58a88453f1b051e8efe5c3ca59e4dc85fe406.png)

**Comment by respinos** [comment]
On the todo list is reviewing just _how_ the `<iframe>` is being constructed and filled. You can see in the inspector that it looks like the document contents are also stuffed in an attribute on the frame.

**Comment by sethaj** [comment]
Right, I see, definitely something wrong here and no real surprise that it's triggering a XSS/permission issue. Kind of crazy it works at all really...

![epub-iframe-generated.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/570be388559d15130075b8b1/125516c66e82c728ace21e0d46ed848f21cf8aaf9de8b246e95af59a2c5426672c00e1673295f127b54778154d555ca9470c5b42fdad8e7fa6e56d71d85a03edd1690a74c43b12bea4905dee5fee7fd616cfe3fe9846d2e93a2fe68e8f49391f031a8df95e3da48b06.png)

**Comment by respinos** [comment]
`srcdoc` is the modern way for adding content to `iframe`; that's a red herring.

The `marks-pane` library copies data into the SVG element's `dataset` property ... which doesn't exist in IE/Edge. Tweaking `marks-pane` to skip that if the SVG element `dataset === undefined`.
