### ISSUE TITLE
Default to scroll mode if mobile

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/cozy-sun-bear#91]
As a user, when I open the reader using a mobile device, default the display to scroll mode to make it easier to reader (less paging required).

**Comment by respinos** [comment]
Should this be based on device orientation? (I've never been sure if HathiTrust's orientation switching was useful or a hindrance).

**Comment by jmcglone** [comment]
Good question. I like this idea but on the other hand it might be too clever. It could be jarring/unwanted to go from scroll to page-by-page without selecting to do so. We'll never really be certain why a user might change device orientation. Looking at iBooks on an iPhone, it maintains whatever view you've selected when switching orientation.
